import Image from "next/image";
import { TrinityLogo } from "@/components/trinity-logo";
import { ArrowDown, ArrowUpRight, CalendarDays, MapPin, Sparkles, Ticket } from "lucide-react";
import Link from "next/link";
import { RegistrationForm } from "@/components/registration-form";

export default function Home() {
  return <main className="site-shell garba-site">
    <nav className="top-nav" aria-label="Main navigation"><Link className="wordmark" href="/" aria-label="DJSCE Trinity home"><TrinityLogo priority /></Link><a className="nav-action" href="#register">Join the celebration <ArrowUpRight size={16} /></a></nav>
    <section className="festival-hero" aria-labelledby="event-title"><div className="hero-copy fade-up"><p className="eyebrow"><span className="live-dot" /> DJSCE Trinity presents</p><h1 id="event-title">garba<span>night<span className="title-star">✦</span></span></h1><p className="hero-tagline">A little tradition.<br />A whole lot of celebration.</p><p className="hero-description">Bring your friends, your festive fits, and your favourite moves. Let’s make it a night to remember.</p><a className="hero-cta" href="#register">Reserve my entry <ArrowUpRight size={19} /></a><span className="hero-caption">One night. All the festive feels.</span></div><div className="art-stage"><Image className="hero-garba-image" src="/images/garba-dancers-transparent.webp" alt="Garba Night artwork with dancers in traditional golden outfits" width={636} height={846} sizes="(max-width: 540px) 320px, (max-width: 800px) 45vw, 540px" priority /><span className="art-note">Dress festive. Dance freely.</span></div></section>
    <section className="event-strip" aria-label="Event details"><div><CalendarDays /><span><small>MARK YOUR CALENDAR</small><strong>9 October 2026</strong><span>Friday · Garba Night</span></span></div><div><MapPin /><span><small>MEET US AT</small><strong>Mukesh Patel Hall</strong><span>Underground</span></span></div><div><Ticket /><span><small>YOUR WAY IN</small><strong>₹149 <em>/ person</em></strong><span className="payment-note">To be paid online only at the registration desk.</span></span></div></section>
    <section className="registration-layout crew-form-first" id="register" aria-labelledby="crew-title"><div className="registration-story crew-heading"><p className="eyebrow">YOUR NIGHT STARTS HERE <ArrowDown size={14} /></p><h2 id="crew-title">A night for<br /><em>your whole crew.</em></h2></div><div className="form-column" id="entry-form"><div className="form-heading"><p className="eyebrow">GARBA NIGHT · 09 OCT 2026</p><h2 id="registration-title">Count me in.</h2><p>Your first step to the dance floor.</p><span className="fee-pill">Entry fee · ₹149 per person</span><p className="payment-note">To be paid online only at the registration desk.</p></div><RegistrationForm /></div><div className="registration-story crew-instructions"><p>Get on the list, save your registration code, and show it at the physical desk to collect your entry pass.</p><ol className="entry-steps"><li><span>01</span><div><strong>Make it official</strong><p>Fill in your details. It only takes a minute.</p></div></li><li><span>02</span><div><strong>Save your code</strong><p>Screenshot your confirmation for easy access.</p></div></li><li><span>03</span><div><strong>Collect your pass & celebrate</strong><p>Visit the physical desk with your code.</p></div></li></ol><div className="festive-note"><Sparkles size={22} /><span>A festive outfit. A familiar face.<br />A new favourite memory.</span></div></div></section>
    <section className="event-about" aria-labelledby="about-title"><figure className="about-art"><Image src="/images/garba-pink-dancers-transparent.webp" alt="Garba dancers in pink and yellow festive outfits playing dandiya" width={600} height={600} sizes="(max-width: 540px) 260px, 318px" /><figcaption>Tradition in every twirl.</figcaption></figure><div className="about-copy"><p className="eyebrow">THE COLOURS. THE ENERGY. THE CELEBRATION.</p><h2 id="about-title">Meet you on<br /><em>the dance floor.</em></h2><p>A celebration of rhythm, colour, and togetherness. Put on your festive best and join your friends for a Garba Night with DJSCE Trinity.</p><div className="about-highlights"><span><Sparkles size={18} /> Festive fits</span><span><Ticket size={18} /> ₹149 entry</span><span><CalendarDays size={18} /> 9 October</span></div><a className="about-link" href="#register">Be part of the celebration <ArrowUpRight size={17} /></a></div></section>
    <div className="celebration-ribbon" aria-hidden="true">DANDIYA <span>✦</span> DOSTI <span>✦</span> DANCE <span>✦</span> DANDIYA <span>✦</span> DOSTI <span>✦</span> DANCE</div>
    <section className="event-faq" aria-label="Event questions"><p className="eyebrow">BEFORE YOU HIT THE FLOOR</p><details><summary>Where is the event?</summary><p>Mukesh Patel Hall (Underground). The event is on Friday, 9 October 2026.</p></details><details><summary>Does registering give me an entry pass?</summary><p>Registration gives you a unique code. Save it and show it at the physical desk to collect your entry pass. The event entry fee is ₹149 per person. To be paid online only at the registration desk.</p></details><details><summary>What should I bring?</summary><p>Keep your registration code handy. Once the desk issues your pass, keep your emailed QR code ready for the gate scanner.</p></details></section>
    <footer className="site-footer"><div className="footer-brand"><p className="footer-caption">Made for a night to remember.</p></div><div><Link href="/admin">Desk portal</Link><Link href="/gate">Gate scanner <ArrowUpRight size={13} /></Link></div></footer>
  </main>;
}
